# Generated by Django 4.0.5 on 2022-07-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_listing_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='listing_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
