# Generated by Django 4.0.5 on 2022-07-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_listing_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Listing_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
