# Generated by Django 4.0.5 on 2022-07-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_listing_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='Watchlisted_Listing', to='auctions.auction_listing'),
        ),
    ]
